[server]
# Dev-only: behind Codespaces proxies, XSRF/CORS can block uploads (403).
enableXsrfProtection = false
enableCORS = false

# Bump limits just in case (MB):
maxUploadSize = 1000  # MB; pick a value big enough for typical workbooks
maxMessageSize = 1024

# For deployments behind a reverse proxy (e.g., Nginx),
# set a matching `client_max_body_size` in that proxy's configuration.

address = "0.0.0.0"
port = 8501

[theme]
primaryColor = "#4F46E5"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#111827"
font = "sans serif"
