[server]
# Dev-only: behind Codespaces proxies, XSRF/CORS can block uploads (403).
enableXsrfProtection = false
enableCORS = false

# Bump limits just in case (MB):
maxUploadSize = 1024
maxMessageSize = 1024

address = "0.0.0.0"
port = 8501
